export const armas=[
    {
        'id':'1',
        'nombre':'espada',
        'ataque':5,
        'puntos':150, 
        'velocidad':300, 
        'tiempoDisparo':0,
        'nivel':1, 
        'diseno':'arma1', 
        'width': 80,
        'heigth':80,
        'largoAtaque':false, 
        'sonido':'ataque1',
        'descripcion':'espada clasica',
        'inicioAnim':0
    },
    {
        'id':'2',
        'nombre':'Rastrillo',
        'ataque':10,
        'puntos':150, 
        'velocidad':400, 
        'tiempoDisparo':0,
        'nivel':1, 
        'width': 50,
        'heigth':80,  
        'diseno':'arma2', 
        'largoAtaque':false, 
        'sonido':'ataque2',
        'descripcion':'Rastrillo para rastrear a la basura',
        'inicioAnim':4
    },
    {
        'id':'3',
        'nombre':'pala',
        'ataque':15,
        'puntos':250, 
        'velocidad':450, 
        'tiempoDisparo':0,
        'nivel':1, 
        'width': 70,
        'heigth':70,  
        'diseno':'arma3', 
        'largoAtaque':false, 
        'sonido':'ataque3',
        'descripcion':'Para escarbar y enterrar a tus enemigos',
        'inicioAnim':8
    },
    {
        'id':'4',
        'nombre':'Guantes de compostaje',
        'ataque':10,
        'puntos':200, 
        'tiempoDisparo':0,
        'velocidad':100, 
        'nivel':1, 
        'width': 30,
        'heigth':30,  
        'diseno':'arma4', 
        'largoAtaque':false, 
        'sonido':'ataque4',
        'descripcion':'Para sembrar plantas, tambien sirven como guantes de boxeo',
        'inicioAnim':12
    },
    {
        'id':'5',
        'nombre':'Lanza Bambu',
        'ataque':15,
        'puntos':300, 
        'tiempoDisparo':100,
        'velocidad':100, 
        'nivel':2, 
        'width': 40,
        'heigth':100,  
        'diseno':'arma5', 
        'largoAtaque':true,
        'sonido':'ataque5', 
        'descripcion':'Comida favorita de los pandas y escencial para la picar la basura ',
        'inicioAnim':16
    },
    {
        'id':'6',
        'nombre':'Soplador de semillas',
        'ataque':10,
        'puntos':300, 
        'tiempoDisparo':200,
        'velocidad':300, 
        'nivel':2, 
        'width': 20,
        'heigth':20,  
        'diseno':'arma6', 
        'largoAtaque':true,
        'sonido':'ataque6', 
        'descripcion':'Util para sembrar lo mas rapido posible y disparar.',
        'inicioAnim':20
    },
    {
        'id':'7',
        'nombre':'Disparador de agua',
        'ataque':5,
        'puntos':300, 
        'tiempoDisparo':450,
        'velocidad':250, 
        'nivel':2, 
        'width': 15,
        'heigth':15,  
        'diseno':'arma7', 
        'largoAtaque':true, 
        'sonido':'ataque7',
        'descripcion':'Sirve para la regar las plantas y para limpiar la suciedad.',
        'inicioAnim':24
    },
    {
        'id':'8',
        'nombre':'Martillo de raices',
        'ataque':30,
        'puntos':600, 
        'tiempoDisparo':0,
        'velocidad':150, 
        'nivel':3, 
        'width': 70,
        'heigth':70,  
        'diseno':'arma8', 
        'largoAtaque':false,
        'sonido':'ataque8', 
        'descripcion':'Util para el trabajo y aplasta.',
        'inicioAnim':28
    },
    {
        'id':'9',
        'nombre':'Lanza Frutas',
        'ataque':45,
        'puntos':600, 
        'tiempoDisparo':300,
        'velocidad':450, 
        'nivel':3, 
        'width': 20,
        'heigth':20,  
        'diseno':'arma9',
        'largoAtaque':true, 
        'sonido':'ataque9',
        'descripcion':'A todos nos gusta la fruta',
        'inicioAnim':32
    },
    {
        'id':'10',
        'nombre':'Cañon de agua',
        'ataque':50,
        'puntos':600, 
        'tiempoDisparo':200,
        'velocidad':600, 
        'nivel':3, 
        'width': 80,
        'heigth':80,  
        'diseno':'arma10', 
        'largoAtaque':true,
        'sonido':'ataque10', 
        'descripcion':'Maquina asesina mortal ultra super poderosa 3000',
        'inicioAnim':36
    },
]